import { Router, type IRouter } from "express";
import healthRouter from "./health";
import authRouter from "./auth";
import registrationRouter from "./registration";
import usersRouter from "./users";
import uploadsRouter from "./uploads";
import newsRouter from "./news";
import bannersRouter from "./banners";
import sliderRouter from "./slider";
import latihanRouter from "./latihan";
import iuranRouter from "./iuran";
import honorRouter from "./honor";
import kasRouter from "./kas";
import kurasiRouter from "./kurasi";
import activityRouter from "./activity";
import pembinaanRouter from "./pembinaan";
import asetRouter from "./aset";
import kerjasamaRouter from "./kerjasamaRoutes";
import sewaRouter from "./sewaRoutes";
import infoBudayaRouter from "./infoBudaya";
import appearanceRouter from "./appearanceRoutes";

const router: IRouter = Router();

router.use(healthRouter);
router.use(authRouter);
router.use(registrationRouter);
router.use(usersRouter);
router.use(uploadsRouter);
router.use(newsRouter);
router.use(bannersRouter);
router.use(sliderRouter);
router.use(latihanRouter);
router.use(iuranRouter);
router.use(honorRouter);
router.use(kasRouter);
router.use(kurasiRouter);
router.use(activityRouter);
router.use(pembinaanRouter);
router.use(asetRouter);
router.use(kerjasamaRouter);
router.use(sewaRouter);
router.use(infoBudayaRouter);
router.use(appearanceRouter);

export default router;
